name: Inner

# This step triggers after the learner creates a new repository from the template.
# This workflow updates from step 0 to step 1.

# This will run every time we create push a commit to `main`.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_call:
    inputs:
      variable:
        type: string
        required: true

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  log:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo ${{ inputs.variable }}

