name: Outer

# This step triggers after every push to welcome-workflow.
# This workflow updates from step 1 to step 2.

# This will run every time we push to welcome-workflow.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  run-inner-workflow:
    uses: ./.github/workflows/inner.yml
    with:
      variable: |
        ${{ matrix.values }}
    strategy:
      matrix:
        values: [
          "1",
          "2"
        ]
